### ISSUE TITLE
Affix组件 固定底部问题

### ISSUE THREAD

**Issue by iygxv** [qq282126990/ivue-ui-vue3#3]
## 描述
代码克隆下来后， 执行yarn serve， 打开页面后， 滚动滚动条， 无法固定在底部
![image](https://user-images.githubusercontent.com/71203208/216279260-cace7bec-da7e-463c-83ce-a97dc3c4ac79.png)

**Comment by qq282126990** [comment]
需要滚动条滚动最上面

**Comment by qq282126990** [comment]
你可能没有理解固定底部的 意思 ，固定底部是向上滚动才会固定在底部

**Comment by qq282126990** [comment]
这个好像确实有问题，下个版本更新

**Comment by qq282126990** [comment]
1.0.6版本已修复，修改为新的逻辑的 affix 组件
